#!/usr/bin/env bash
# display information about subdomains
# usage: ./dns_info.sh <domain> <subdomain>
# use atleast 1 bash function

domain="$1"
subdomain="$2"

function get_dns_info {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dig_output=$(dig +short "$sub"."$domain")
        record_type=$(dig +short -t CNAME "$sub"."$domain" | grep -q "CNAME" && echo "CNAME" || echo "A")
        destination=$(echo "$dig_output" | awk 'NR==1 {print $1}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

get_dns_info "$domain" "$subdomain"
