#!/usr/bin/env bash
# display information about subdomains

#!/bin/bash

domain="$1"
subdomain="$2"

function get_dns_info {
    local domain="$1"
    local subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short "$sub"."$domain" | awk 'NR==1 {print $4}')
        destination=$(dig +short "$sub"."$domain")
        echo "The subdomain $sub.$domain is a $record_type record and points to $destination"
    done
}

get_dns_info "$domain" "$subdomain"
