#!/usr/bin/env bash
# transfer files from locale to remote server
# Define variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

if ["$#" -lt 3]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
  elif [ ! -f "$PATH_TO_SSH_KEY" ]; then
    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":/home/"$USERNAME"/
fi

# Transfer file
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":/home/"$USERNAME"/


