#!/usr/bin/env bash
# transfer files from locale to remote server
# Define variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

if [ -z "$client_file_path" ] || [ -z "$server_address" ] || [ -z "$username" ] || [ -z "$ssh_key_path" ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer file
scp -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":/home/"$USERNAME"/


