#!/usr/bin/env bash
# install and configure nginx web server

# install nginx
apt-get -y update
apt-get -y install nginx

# alow NGINX to listen on port 80
ufw allow 'Nginx HTTP'

# Change content of /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# start nginx
service nginx start

# configure nginx to redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4

sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 parmanent;/' /etc/nginx/sites-enabled/default
service nginx restart

