#!/usr/bin/env bash
# create filename containing PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ >/var/run/myscript.pid

function sigterm_handler() {
    echo "I hate the kill command"
    exit 0
}

function sigint_handler() {
    echo "Y U no love me?!"
}

function sigquit_handler() {
    rm /var/run/myscript.pid
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# Main loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
