#!/usr/bin/env bash
# This script prints Bash School 10 times

i=1
while [ $i -le 100 ]; do
    if (($i % 15 == 0)); then
        echo FizzBuzz
    elif (( $i % 3 == 0 )); then
        echo Fizz
    elif (( $i % 5 == 0 )); then
        echo Buzz
    else
        echo $i
    fi
    ((i += 1))
done
