#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

while read -r line; do
    username=$(echo "$line" | cut -d: -f1)
    uid=$(echo "$line" | cut -d: -f3)
    homedir=$(echo "$line" | cut -d: -f6)
    echo "$username"
    echo "$uid"
    echo "$homedir"
done </etc/passwd
