#!/usr/bin/env bash
# This script prints Bash School 10 times

i=1
while [ $i -le 10 ]; do
    if [ $i == 4 ]; then
        echo bad luck
    elif [ $i == 9 ]; then
        echo good luck
    else
        echo "Best School"
    fi
    ((i += 1))
done
