#!/usr/bin/env bash
# This script prints Bash School 10 times

i=1
while [ $i -le 10 ]; do
    echo "Best School"
    if [ $i == 4 ]; then
        echo bad luck
    fi
    if [ $i == 9 ]; then
        echo good luck
    fi
    ((i += 1))
done
