#!/usr/bin/env bash
# This script prints Bash School 10 times

i=1
j=1
while [ $i -le 12 ]; do
    echo Hour: $i
    while [ $j -le 59 ]; do
        echo $j
        ((j += 1))
    done
    j=1
    ((i += 1))
done
