#!/usr/bin/env bash
# This script prints Bash School 10 times

i=1
while [ $i -le 12 ]; do
    echo hour: $i
    j=1
    while [ $j -le 60 ]; do
        echo $j
        ((j += 1))
    done
    ((i += 1))
done
